### ISSUE TITLE
Support for GPT-2

### ISSUE THREAD

**Issue by pabl-o-ce** [rustformers/llmcord#22]
I have been trying to use GPT-2 models setting on the `config.toml`:

```toml
[model]
path = "/usr/src/llmcord/weights/wizardcoder-guanaco-15b-v1.1.ggmlv1.q8_0.bin"
context_token_length = 2048
architecture = "GPT-2"
prefer_mmap = true
```
I'm getting zero response at the moment I try it.

I think `llmcord` don't support right now `GPT-2`?

Any help is gladly received.
